"""Pure domain contracts for GAMR."""

from .datasets import (
    DatasetDocument,
    DatasetManifest,
    DatasetVariable,
    DiscoveryPlan,
    EvaluationPlan,
    PromptBundle,
    Scenario,
    escape_unknown_template_placeholders,
    load_manifest,
    load_scenario,
    render_template,
    validate_document,
    validate_template_placeholders,
)
from .events import (
    ActivityId,
    ActivityType,
    Availability,
    EvidenceId,
    EvidenceItem,
    EvidenceQuery,
    EvidenceType,
    ParticipantId,
    ParticipantKind,
    RunActivity,
    RunEvent,
    RunId,
    RunParticipant,
)
from .experiments import (
    CaseResult,
    DatasetReference,
    Evidence,
    ExperimentConfig,
    ExperimentRecord,
    ResultSummary,
    RunRecord,
    RunResult,
    RunSource,
)
from .states import ExecutionOutcome, ObjectiveStatus, RunState, SecurityVerdict, transition
from .workflow import CaseAssessment, DiscoveryCandidate, NextTurnDecision

__all__ = [
    "CaseResult",
    "CaseAssessment",
    "DatasetManifest",
    "DatasetDocument",
    "DatasetVariable",
    "DatasetReference",
    "DiscoveryPlan",
    "DiscoveryCandidate",
    "EvaluationPlan",
    "Evidence",
    "ExecutionOutcome",
    "ObjectiveStatus",
    "NextTurnDecision",
    "ExperimentConfig",
    "ExperimentRecord",
    "RunRecord",
    "RunResult",
    "RunSource",
    "RunEvent",
    "RunActivity",
    "RunParticipant",
    "EvidenceItem",
    "EvidenceQuery",
    "ActivityType",
    "EvidenceType",
    "Availability",
    "ParticipantKind",
    "ActivityId",
    "RunId",
    "ParticipantId",
    "EvidenceId",
    "ResultSummary",
    "RunState",
    "PromptBundle",
    "Scenario",
    "SecurityVerdict",
    "load_manifest",
    "load_scenario",
    "transition",
    "escape_unknown_template_placeholders",
    "render_template",
    "validate_document",
    "validate_template_placeholders",
]
